Code/projet_club_sportif/Controllers/extrasController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using projet_club_sportif.Models;

namespace projet_club_sportif.Controllers
{
    [Authorize]
    public class extrasController : Controller
    {
        private Extra extra;
        private LieuDAO lieuDao;

        public extrasController() : this(new Extra(), new LieuDAO())
        {

        }

        private extrasController(Extra UnExtra, LieuDAO UnLieuDao)
        {
            extra = UnExtra;
            lieuDao = UnLieuDao;
        }

        // GET: extras
        public ActionResult Index()
        {
            var extras = extra.GetAll();

            return View(extras.ToList());
        }

        // GET: extras/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Extra myExtra = extra.Find((int)id);
            if (extra == null)
            {
                return HttpNotFound();
            }
            return View(myExtra);
        }

        // GET: extras/Create
        public ActionResult Create()
        {
            ViewBag.lieux = lieuDao.GetAllForEvents();

            return View(extra);
        }

        // POST: extras/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Extra unExtra)
        {
            if (ModelState.IsValid)
            {
                extra.Create(unExtra);
                return RedirectToAction("Index");
            }

            return View(extra);
        }

        // GET: extras/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            extra.Find((int)id);
            if (extra == null)
            {
                return HttpNotFound();
            }

            ViewBag.lieux = lieuDao.GetAllForEvents();

            return View(extra);
        }

        // POST: extras/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Extra unExtra)
        {
            if (ModelState.IsValid)
            {
                extra.Find(unExtra.fk_evenement);
                extra.Update(unExtra);
                return RedirectToAction("Index");
            }

            return View(extra);
        }

        // GET: extras/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            extra.Find((int)id);
            if (extra == null)
            {
                return HttpNotFound();
            }
            return View(extra);
        }

        // POST: extras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            extra.Find(id);
            extra.Delete();
            return RedirectToAction("Index");
        }
    }
}

Code/projet_club_sportif/Controllers/lieuxController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using projet_club_sportif.Models;

namespace projet_club_sportif.Controllers
{
    [Authorize]
    public class lieuxController : Controller
    {
        private LieuDAO lieuDao;

        public lieuxController() : this(new LieuDAO())
        {

        }

        private lieuxController(LieuDAO UnLieuDao)
        {
            lieuDao = UnLieuDao;
        }

        // GET: lieux
        public ActionResult Index()
        {
            return View(lieuDao.GetAllForEvents().ToList());
        }

        // GET: lieux/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Lieu lieu = lieuDao.Find((int)id);
            if (lieu == null)
            {
                return HttpNotFound();
            }
            return View(lieu);
        }

        // GET: lieux/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: lieux/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(T_Lieu lieu)
        {
            lieu.residentielle = false;
            if (ModelState.IsValid)
            {
                lieuDao.Create(lieu);
                return RedirectToAction("Index");
            }

            return View(lieu);
        }

        // GET: lieux/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Lieu lieu = lieuDao.Find((int)id);
            if (lieu == null)
            {
                return HttpNotFound();
            }
            return View(lieu);
        }

        // POST: lieux/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(T_Lieu lieu)
        {
            lieu.residentielle = false;

            if (ModelState.IsValid)
            {
                lieuDao.Update(lieu);
                return RedirectToAction("Index");
            }
            return View(lieu);
        }

        // GET: lieux/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Lieu lieu = lieuDao.Find((int)id);
            if (lieu == null)
            {
                return HttpNotFound();
            }
            return View(lieu);
        }

        // POST: lieux/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            T_Lieu lieu = lieuDao.Find(id);
            lieuDao.Delete(lieu);
            return RedirectToAction("Index");
        }

    }
}

Code/projet_club_sportif/Controllers/stagesController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using projet_club_sportif.Models;

namespace projet_club_sportif.Controllers
{
    [Authorize]
    public class stagesController : Controller
    {
        private Stage stage;
        private LieuDAO lieuDao;

        public stagesController() : this(new Stage(), new LieuDAO())
        {

        }

        private stagesController(Stage unStage, LieuDAO UnLieuDao)
        {
            stage = unStage;
            lieuDao = UnLieuDao;
        }

        // GET: stages
        public ActionResult Index()
        {
            var stages = stage.GetAll();
            return View(stages.ToList());
        }

        // GET: stages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            stage.Find((int)id);
            if (stage == null)
            {
                return HttpNotFound();
            }
            return View(stage);
        }

        // GET: stages/Create
        public ActionResult Create()
        {
            ViewBag.lieux = lieuDao.GetAllForEvents();

            return View(stage);
        }

        // POST: stages/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Stage unStage)
        {
            if (ModelState.IsValid)
            {
                stage.Create(unStage);
                return RedirectToAction("Index");
            }

            return View(stage);
        }

        // GET: stages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            stage.Find((int) id);
            if (stage == null)
            {
                return HttpNotFound();
            }

            ViewBag.lieux = lieuDao.GetAllForEvents();

            return View(stage);
        }

        // POST: stages/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Stage unStage)
        {
            if (ModelState.IsValid)
            {
                stage.Find(unStage.fk_evenement);
                stage.Update(unStage);
                return RedirectToAction("Index");
            }

            return View(stage);
        }

        // GET: stages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            stage = stage.Find((int) id);
            if (stage == null)
            {
                return HttpNotFound();
            }
            return View(stage);
        }

        // POST: stages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            stage.Find(id);
            stage.Delete();
            return RedirectToAction("Index");
        }

    }
}

Code/projet_club_sportif/Controllers/themesController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using projet_club_sportif.Models;

namespace projet_club_sportif.Controllers
{
    [Authorize]
    public class themesController : Controller
    {
        private DAO<T_Theme> themeDao;

        public themesController() : this(new ThemeDAO())
        {

        }

        private themesController(ThemeDAO UnThemeDao)
        {
            themeDao = UnThemeDao;
        }

        // GET: themes
        public ActionResult Index()
        {
            return View(themeDao.GetAll().ToList());
        }

        // GET: themes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Theme unTheme = themeDao.Find((int) id);
            if (unTheme == null)
            {
                return HttpNotFound();
            }
            return View(unTheme);
        }

        // GET: themes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: themes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(T_Theme unTheme)
        {
            if (ModelState.IsValid)
            {
                themeDao.Create(unTheme);
                return RedirectToAction("Index");
            }

            return View(unTheme);
        }

        // GET: themes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Theme theme = themeDao.Find((int) id);
            if (theme == null)
            {
                return HttpNotFound();
            }
            return View(theme);
        }

        // POST: themes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(T_Theme unTheme)
        {
            if (ModelState.IsValid)
            {
                themeDao.Update(unTheme);
                return RedirectToAction("Index");
            }
            return View(unTheme);
        }

        // GET: themes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Theme unTheme = themeDao.Find((int) id);
            if (unTheme == null)
            {
                return HttpNotFound();
            }
            return View(unTheme);
        }

        // POST: themes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            T_Theme unTheme = themeDao.Find(id);
            themeDao.Delete(unTheme);
            return RedirectToAction("Index");
        }
    }
}

Code/projet_club_sportif/Views/menu/Eleve_Consulter_Son_Historique.cshtml
@{
    ViewBag.Title = "Eleve";
    var i = 0;
}

<h2>Consulter son historique</h2>


<ul class="nav nav-pills">
    <li role="presentation" class="active"><a href="/compte/DetailsPDF?id=@ViewBag.Personne.pk_personne"><span class="glyphicon glyphicon-list-alt"></span> Imprimer en PDF</a></li>
</ul>

<h4>Donnée personnel</h4>
<hr />
<dl class="dl-horizontal">

    <dt>
        ceinture:
    <dt>
    <dd>
       @*@Html.DisplayFor(projet_club_sportif.Models.Personne => ViewBag.Personne.grade);*@
        @{
            projet_club_sportif.Models.Personne laPersonne = ViewBag.Personne;
        }
        @Html.DisplayFor(Model => laPersonne.grade)
    </dd>
    <dt>
        poids:
   </dt>
    <dd>
        @ViewBag.Personne.poids
    </dd>
    <dt>
        age:
    </dt>
    <dd>
        @ViewBag.Personne.age
    </dd>
       
</dl>
@if (ViewBag.Cours != null && ViewBag.Cours.Count != 0)
{
    <h4>cours</h4>
    <hr />
        <table class="table">
            <tr>
                <th>
                   Section
                </th>
                <th>
                    Themes
                </th>
                <th>
                    Date de début
                </th>
                <th>
                    Date de fin
                </th>
            </tr>
            @foreach (projet_club_sportif.Models.Cours item in ViewBag.Cours)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => item.myCours.section)
                    </td>
                    <td>
                       @Html.DisplayFor(model => item.themesSelectedId, "ListTThemes")
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.dateDebut)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.dateFin)
                    </td>
                </tr>
            }
        </table>
}
@if (ViewBag.Examen != null && ViewBag.Examen.Count != 0)
{
    <h4>Examen</h4>
    <hr />
    <table class="table">
        <tr>
            <th>
                Grade
            </th>
            <th>
                Date de début
            </th>
            <th>
                Date de fin
            </th>
            <th>
                Statut
            </th>
        </tr>
        @foreach (projet_club_sportif.Models.Examen item in ViewBag.Examen)
        {
            <tr>
                <td>
                   @Html.DisplayFor(Examen => item.grade)
                </td>
                <td>
                    @Html.DisplayFor(Examen => item.dateDebut)
                </td>
                <td>
                    @Html.DisplayFor(Examen => item.dateFin)
                </td>
                <td>
                    @ViewBag.Reussit[i++]
                </td>
            </tr>
        }
    </table>
}
@if (ViewBag.Competition != null && ViewBag.Competition.Count != 0)
{
    <h4>competition</h4>
        <hr />
        <table class="table">
            <tr>
                <th>
                    Titre
                </th>
                <th>
                    Categories
                </th>
                <th>
                    Date de début
                </th>
                <th>
                    Date de fin
                </th>
                <th>
                    Prix
                </th>
            </tr>
          @foreach (projet_club_sportif.Models.Competition item in ViewBag.Competition)
          {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.titre)
                </td>
                <td>
                    @Html.DisplayFor(model => item.categoriesSelectedId, "ListTCategories")
                </td>
                <td>
                    @Html.DisplayFor(model => item.dateDebut)
                </td>
                <td>
                    @Html.DisplayFor(model => item.dateFin)
                </td>
                <td>
                    @Html.DisplayFor(model => item.listPrix, "ListTPrixCompetition")
                </td>
            </tr>
          }
        </table>
}
@if (ViewBag.Extra != null && ViewBag.Extra.Count != 0)
{
    <h4>Extra</h4>
    <hr />

    <table class="table">
        <tr>
            <th>
                Titre
            </th>
            <th>
                categories
            </th>
            <th>
                Date de début
            </th>
            <th></th>
        </tr>
        @foreach (var item in ViewBag.Extra)
        {
            <tr>
                <td>
                    @item.titre
                </td>
                <td>
                    @Html.Raw(item.dateDebut.ToString("dd/MM/yyyy HH:mm"))
                </td>
                <td>
                    @Html.Raw(item.dateFin.ToString("dd/MM/yyyy HH:mm"))
                </td>
            </tr>
        }
    </table>
}



@if (ViewBag.Stage != null && ViewBag.Stage.Count != 0)
{
    <h4>Stage</h4>
    <hr />

    <table class="table">
            <tr>
                <th>
                    Thèmes
                </th>
                <th>
                    Date de début
                </th>
                <th>
                    Date de fin
                </th>
                <th></th>
            </tr>
        @foreach (projet_club_sportif.Models.Stage item in ViewBag.Stage)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.themesSelectedId, "ListTThemes")
                </td>
                <td>
                    @Html.Raw(item.dateDebut.ToString("dd/MM/yyyy HH:mm"))
                </td>
                <td>
                    @Html.Raw(item.dateFin.ToString("dd/MM/yyyy HH:mm"))
                </td>
            </tr>
        }
        </table>
}
    <div>
        @Html.ActionLink("Retour", "Index", "menu")
    </div>
@section scripts
{
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/historique/pdf.js"></script>

}

Code/projet_club_sportif/Views/menu/Gerer_Ses_Inscriptions.cshtml
@{
    ViewBag.Title = "Gérer ses inscriptions :";
}

<h2>Gérer ses inscriptions</h2>
<div id="menu-membre">
    <ul id="affiche">
        <li>@Html.ActionLink("S'inscire à un événement", "S_Inscrire_A_Un_Evenement", "menu")</li>
        <li>@Html.ActionLink("Se Désinscrire d'un événement", "Se_Desinscrire_D_Un_Evenement", "menu")</li>
        <li>@Html.ActionLink("Consulter la liste de ses inscriptions", "Liste_Inscriptions", "participers")</li>
    </ul>
</div>

Code/projet_club_sportif/Views/menu/Instructeur_Consulter_Son_Historique.cshtml
@{
    ViewBag.Title = "Eleve";
    var i = 0;
}

<h2>Consulter son historique</h2>

<ul class="nav nav-pills">
  <li role="presentation" class="active"><a href="/compte/DetailsPDF?id=@ViewBag.Personne.pk_personne"><span class="glyphicon glyphicon-list-alt"></span> Imprimer en PDF</a></li>
</ul>

<h4>Donnée personnel</h4>
<hr />
<dl class="dl-horizontal">

    <dt>
        ceinture:
    <dt>
    <dd>
        @{ 
            projet_club_sportif.Models.Personne laPersonne = ViewBag.Personne;
        }
        @Html.DisplayFor(Model => laPersonne.grade)
    </dd>
    <dt>
        poids:
    </dt>
    <dd>
        @ViewBag.Personne.poids
    </dd>
    <dt>
        age:
    </dt>
    <dd>
        @ViewBag.Personne.age
    </dd>

</dl>

@if (ViewBag.Cours != null && ViewBag.Cours.Count != 0)
{
    <h4>cours</h4>
    <hr />
    <table class="table">
        <tr>
            <th>
                Section
            </th>
            <th>
                Themes
            </th>
            <th>
                Date de début
            </th>
            <th>
                Date de fin
            </th>
        </tr>
        @foreach (projet_club_sportif.Models.Cours item in ViewBag.Cours)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.myCours.section)
                </td>
                <td>
                    @Html.DisplayFor(model => item.themesSelectedId, "ListTThemes")
                </td>
                <td>
                    @Html.DisplayFor(model => item.dateDebut)
                </td>
                <td>
                    @Html.DisplayFor(model => item.dateFin)
                </td>
            </tr>
        }
    </table>
}
@if (ViewBag.Examen != null && ViewBag.Examen.Count != 0)
{
    <h4>Examen</h4>
    <hr />
    <table class="table">
        <tr>
            <th>
                Grade
            </th>
            <th>
                Date de début
            </th>
            <th>
                Date de fin
            </th>
            <th>
                réussi
            </th>
        </tr>
        @foreach (projet_club_sportif.Models.Examen item in ViewBag.Examen)
        {
            <tr>
                <td>
                    @Html.DisplayFor(Examen => item.grade)
                </td>
                <td>
                    @Html.DisplayFor(Examen => item.dateDebut)
                </td>
                <td>
                    @Html.DisplayFor(Examen => item.dateFin)
                </td>
                <td>
                    @ViewBag.Reussit[i++]
                </td>
            </tr>
        }
    </table>
}

@if (ViewBag.Competition != null && ViewBag.Competition.Count != 0)
{
    <h4>competition</h4>
    <hr />
        <table class="table">
            <tr>
                <th>
                    Titre
                </th>
                <th>
                    Categories
                </th>
                <th>
                    Date de début
                </th>
                <th>
                    Date de fin
                </th>
                <th>
                    Prix
                </th>
            </tr>
            @foreach (projet_club_sportif.Models.Competition item in ViewBag.Competition)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => item.titre)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.categoriesSelectedId, "ListTCategories")
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.dateDebut)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.dateFin)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.listPrix, "ListTPrixCompetition")
                    </td>
                </tr>
            }
        </table>
}
@if (ViewBag.Extra != null && ViewBag.Extra.Count != 0)
{
    <h4>Extra</h4>
    <hr />

    <table class="table">
        <tr>
            <th>
                Titre
            </th>
            <th>
                categories
            </th>
            <th>
                Date de début
            </th>
            <th></th>
        </tr>
        @foreach (var item in ViewBag.Extra)
        {
            <tr>
                <td>
                    @item.titre
                </td>
                <td>
                    @Html.Raw(item.dateDebut.ToString("dd/MM/yyyy HH:mm"))
                </td>
                <td>
                    @Html.Raw(item.dateFin.ToString("dd/MM/yyyy HH:mm"))
                </td>
            </tr>
        }
    </table>
}



@if (ViewBag.Stage != null && ViewBag.Stage.Count != 0)
{
    <h4>Stage</h4>
    <hr />

    <table class="table">
        <tr>
            <th>
                Thèmes
            </th>
            <th>
                Date de début
            </th>
            <th>
                Date de fin
            </th>
            <th></th>
        </tr>
        @foreach (projet_club_sportif.Models.Stage item in ViewBag.Stage)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.themesSelectedId, "ListTThemes")
                </td>
                <td>
                    @Html.Raw(item.dateDebut.ToString("dd/MM/yyyy HH:mm"))
                </td>
                <td>
                    @Html.Raw(item.dateFin.ToString("dd/MM/yyyy HH:mm"))
                </td>
            </tr>
        }
    </table>
}


<div>
    @Html.ActionLink("Retour", "Index",  "menu")
</div>

@section scripts
{
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/historique/pdf.js"></script>

}

Code/projet_club_sportif/Views/menu/Instructeur_Gerer_Historique.cshtml
@{
    ViewBag.Title = "Instructeur_Gerer_Historique";
}

<h2>Menu de L'historique</h2>
<div id="menu-membre">
    <ul id="affiche">
        <li>@Html.ActionLink("Consulter son historique", "Instructeur_Consulter_Son_Historique", "menu")</li>
        <li>@Html.ActionLink("Consulter l'historique d'un pratiquant", "Instructeur_consulter_historique_etudiant", "menu")</li>
    </ul>
</div>

Code/projet_club_sportif/Views/menu/Instructeur_Gerer_Inscription_Eleve.cshtml
@{
    ViewBag.Title = "Instructeur_Gerer_Inscription_Eleve";
}

<h2>Gestion des inscriptions/désinscriptions d'un pratiquant</h2>
<div id="menu-membre">
    <ul id="affiche">
        <li>@Html.ActionLink("Inscrire un pratiquant", "RegistrationList", "adminRegistration")</li>
        <li>@Html.ActionLink("Désinscrire un pratiquant", "DeregistrationList", "adminRegistration")</li>
        <li>@Html.ActionLink("Liste des événements auxquels participent un pratiquant", "studentList", "adminRegistration")</li>
    </ul>
</div>

<div>
    @Html.ActionLink("Retour", "Index", "menu")
</div>

@section scripts
{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Code/projet_club_sportif/Views/menu/Instructeur_Gerer_Les_Evenements.cshtml
@{
    ViewBag.Title = "Eleve";
}

<h2>Gérer les évènements</h2>

<div id="menu-membre">
    <ul>
        <li>@Html.ActionLink("Gérer les cours et examens associés", "Index", "cours_et_examen")</li>
        <li>@Html.ActionLink("Gérer les évènements extras", "Index", "extras")</li>
        <li>@Html.ActionLink("Gérer les compétitions", "Index", "competitions")</li>
        <li>@Html.ActionLink("Gérer les stages", "Index", "stages")</li>
    </ul>
</div>

<ul>
    <li>@Html.ActionLink("Gérer les thèmes", "Index", "themes")</li>
    <li>@Html.ActionLink("Gérer les catégories", "Index", "categories")</li>
    <li>@Html.ActionLink("Gérer les lieux", "Index", "lieux")</li>
</ul>

<div>
    @Html.ActionLink("Retour", "Index",  "menu")
</div>

Code/projet_club_sportif/Views/menu/S_Inscrire_A_Un_Evenement.cshtml
@model IEnumerable<projet_club_sportif.Models.T_Evenement>

<h2>S'inscrire à un évènement</h2>
<div id="menu-membre">
    <ul id="affiche">
        <li>@Html.ActionLink("S'inscrire à un cours", "InscriptionCours", "participers")</li>
        <li>@Html.ActionLink("S'inscrire à une compétition", "ChoiceCategory", "participers")</li>
        <li>@Html.ActionLink("S'inscrire à un extra", "InscriptionExtra", "participers")</li>
        <li>@Html.ActionLink("S'inscrire à un examen", "InscriptionExamen", "participers")</li>
        <li>@Html.ActionLink("S'inscrire à un stage", "InscriptionStage", "participers")</li>
    </ul>
</div>

<div>
    @Html.ActionLink("Retour", "Gerer_Ses_Inscriptions", "menu")
</div>

Code/projet_club_sportif/Views/menu/Se_Desinscrire_D_Un_Evenement.cshtml
@model IEnumerable<projet_club_sportif.Models.T_Evenement>
@{
    ViewBag.Title = "Eleve";
}

<h2>Se désinscrire d'un évènement</h2>
<div id="menu-membre">
    <ul id="affiche">
        <li>@Html.ActionLink("Se désinscrire d'un cours", "DesinscriptionCours", "participers")</li>
        <li>@Html.ActionLink("Se désinscrire d'une compétition", "DesinscriptionCompetition", "participers")</li>
        <li>@Html.ActionLink("Se désinscrire d'un extra", "DesinscriptionExtra", "participers")</li>
        <li>@Html.ActionLink("Se désinscrire d'un examen ", "DesinscriptionExamen", "participers")</li>
        <li>@Html.ActionLink("Se désinscrire d'un stage", "DesinscriptionStage", "participers")</li>
    </ul>
</div>

    <div>
        @Html.ActionLink("Retour", "Gerer_Ses_Inscriptions", "menu")
    </div>

Code/projet_club_sportif/Views/menu/modifier_historique_competition.cshtml
@{
    ViewBag.Title = "modifier_historique";
    projet_club_sportif.Models.Personne laPersonne = ViewBag.Personne;
}

<h2>modifier_historique de @ViewBag.Personne.nom @ViewBag.Personne.prenom</h2>
<hr />



<div>
    @Html.ActionLink("Retour", "Index", "menu")
</div>