Code/projet_club_sportif/Controllers/cours_et_examenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using projet_club_sportif.Models;

namespace projet_club_sportif.Controllers
{
    [Authorize]
    public class cours_et_examenController : Controller
    {
        private Cours_Examen CoursExamen;
        private LieuDAO lieuDao;

        public cours_et_examenController() : this(new Cours_Examen(), new LieuDAO())
        {

        }

        private cours_et_examenController(Cours_Examen UnCoursExamen, LieuDAO UnLieuDao)
        {
            CoursExamen = UnCoursExamen;
            lieuDao = UnLieuDao;
        }

        // GET: cours
        public ActionResult Index()
        {
            List<Cours_Examen> coursEtExamens = CoursExamen.GetAll();
            return View(coursEtExamens.ToList());
        }

        // GET: cours/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours_Examen myCursus = CoursExamen.FindByCours((int)id);
            if (CoursExamen == null)
            {
                return HttpNotFound();
            }

            return View(myCursus);
        }

        /// <summary>
        ///affiche la page de création d'un nouveau cours
        /// </summary>
        /// <param name=""></param>
        /// <returns>View</returns>
        // GET: cours/Create
        public ActionResult Create()
        {
            ViewBag.lieux = lieuDao.GetAllForEvents();
            //retourne CoursExamen pour pouvoir afficher la liste des themes ect

            return View(CoursExamen);
        }


        /// <summary>
        ///affiche les champs pour un exam
        /// </summary>
        /// <param name=""></param>
        /// <returns>View</returns>
        // GET: cours/GetExamForm
        public ActionResult GetExamForm(int num)
        {
            //retourne un exam pour pouvoir afficher la liste des exams
            ViewBag.numExam = num;
            ViewBag.lieux = lieuDao.GetAllForEvents();

            return View(CoursExamen);
        }

        /// <summary>
        /// arrange l'object cours_examen, le valide et créé le cours
        /// </summary>
        /// <param name="UnCoursExamen"></param>
        /// <returns></returns>
        // POST: cours/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cours_Examen unCours_Examen)
        {
            //variables
            var form = Request.Form;

            //partie cours
            unCours_Examen.myCours.section = (SECTION?)Convert.ToInt32(form.Get("myCours.section"));
            unCours_Examen.myCours.dateDebut = Convert.ToDateTime(form.Get("myCours.dateDebut"));
            unCours_Examen.myCours.dateFin = Convert.ToDateTime(form.Get("myCours.dateFin"));
            unCours_Examen.myCours.jour = (JOUR?)Convert.ToInt32(form.Get("myCours.jour"));
            unCours_Examen.myCours.fk_lieu = Convert.ToInt32(form.Get("myCours.fk_lieu"));
            unCours_Examen.myCours.description = form.Get("myCours.description");
            //pour les themes du cours
            string[] themesArray = form.GetValues("myCours.themesSelectedId");
            if (themesArray != null)
            {
                foreach (string s in themesArray)
                {
                    unCours_Examen.myCours.themesSelectedId.Add(int.Parse(s));
                }
            }
            //pour les organisateurs du cours
            string[] organisateursCoursArray = form.GetValues("myCours.organisateursSelectedId");
            if (organisateursCoursArray != null)
            {
                foreach (string s in organisateursCoursArray)
                {
                    unCours_Examen.myCours.organisateursSelectedId.Add(int.Parse(s));
                }
            }


            //partie examens
            string[] arrayIndex = form.GetValues("Index");
            unCours_Examen.myExamens.Clear();//?
            foreach (string unIndex in arrayIndex)
            {
                Examen unExamen = new Examen();

                unExamen.grade = (GRADE?)Convert.ToInt32(form.Get("grade["+ unIndex +"]"));
                unExamen.fk_evenement = Convert.ToInt32(form.Get("fk_evenement[" + unIndex + "]"));
                unExamen.dateDebut = Convert.ToDateTime(form.Get("dateDebutExamen[" + unIndex + "]"));
                unExamen.dateFin = Convert.ToDateTime(form.Get("dateFinExamen[" + unIndex + "]"));
                unExamen.fk_lieu = Convert.ToInt32(form.Get("fk_lieu[" + unIndex + "]"));
                unExamen.description = form.Get("description[" + unIndex + "]");

                //pour les organisateurs de l'examen
                unExamen.organisateursSelectedId.Clear();
                string[] organisateursExamArray = form.GetValues("organisateursSelectedId[" + unIndex + "]");
                if (organisateursCoursArray != null)
                {
                    foreach (string s in organisateursExamArray)
                    {
                        unExamen.organisateursSelectedId.Add(int.Parse(s));
                    }
                }

                unCours_Examen.myExamens.Add(unExamen);
            }

            //validation
            ModelState.Clear();
            TryValidateModel(unCours_Examen);

            if (ModelState.IsValid)
            {
                CoursExamen.Create(unCours_Examen);
                return RedirectToAction("Index");
            }

            return View(CoursExamen);
        }

        // GET: cours/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CoursExamen.FindByCours((int)id);

            if (CoursExamen == null)
            {
                return HttpNotFound();
            }

            ViewBag.lieux = lieuDao.GetAllForEvents();

            return View(CoursExamen);
        }

        // POST: cours/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Cours_Examen unCours_Examen)
        {
            var form = Request.Form;

            //bind du cours
            unCours_Examen.myCours.fk_evenement = Convert.ToInt32(form.Get("myCours.fk_evenement"));
            unCours_Examen.myCours.section = (SECTION?)Convert.ToInt32(form.Get("myCours.section"));
            unCours_Examen.myCours.dateDebut = Convert.ToDateTime(form.Get("myCours.dateDebut"));
            unCours_Examen.myCours.dateFin = Convert.ToDateTime(form.Get("myCours.dateFin"));
            unCours_Examen.myCours.jour = (JOUR?)Convert.ToInt32(form.Get("myCours.jour"));
            unCours_Examen.myCours.fk_lieu = Convert.ToInt32(form.Get("myCours.fk_lieu"));
            unCours_Examen.myCours.description = form.Get("myCours.description");

            //pour les themes du cours
            unCours_Examen.myCours.themesSelectedId.Clear();
            string[] themesArray = form.GetValues("myCours.themesSelectedId");
            if (themesArray != null)
            {
                foreach (string s in themesArray)
                {
                    unCours_Examen.myCours.themesSelectedId.Add(int.Parse(s));
                }
            }
            //pour les organisateurs du cours
            unCours_Examen.myCours.organisateursSelectedId.Clear();
            string[] organisateursCoursArray = form.GetValues("myCours.organisateursSelectedId");
            if (organisateursCoursArray != null)
            {
                foreach (string s in organisateursCoursArray)
                {
                    unCours_Examen.myCours.organisateursSelectedId.Add(int.Parse(s));
                }
            }


            string[] arrayIndex = form.GetValues("Index");
            unCours_Examen.myExamens.Clear();
            foreach (string unIndex in arrayIndex)
            {
                Examen unExamen = new Examen();

                unExamen.fk_cours = unCours_Examen.myCours.fk_evenement;
                unExamen.grade = (GRADE?)Convert.ToInt32(form.Get("grade[" + unIndex + "]"));
                unExamen.fk_evenement = Convert.ToInt32(form.Get("fk_evenement[" + unIndex + "]"));
                unExamen.dateDebut = Convert.ToDateTime(form.Get("dateDebutExamen[" + unIndex + "]"));
                unExamen.dateFin = Convert.ToDateTime(form.Get("dateFinExamen[" + unIndex + "]"));
                unExamen.fk_lieu = Convert.ToInt32(form.Get("fk_lieu[" + unIndex + "]"));
                unExamen.description = form.Get("description[" + unIndex + "]");
                //pour les organisateurs de l'examen
                unExamen.organisateursSelectedId.Clear();
                string[] organisateursExamArray = form.GetValues("organisateursSelectedId[" + unIndex + "]");
                if (organisateursCoursArray != null)
                {
                    foreach (string s in organisateursExamArray)
                    {
                        unExamen.organisateursSelectedId.Add(int.Parse(s));
                    }
                }

                unCours_Examen.myExamens.Add(unExamen);
            }

            //validation
            ModelState.Clear();
            TryValidateModel(unCours_Examen);

            if (ModelState.IsValid)
            {
                CoursExamen.FindByCours(Convert.ToInt32(form.Get("myCours.fk_evenement")));
                CoursExamen.Update(unCours_Examen);
                return RedirectToAction("Index");
            }

            return View(CoursExamen);
        }

        // GET: cours/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CoursExamen.FindByCours((int)id);

Code/projet_club_sportif/Controllers/stagesController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using projet_club_sportif.Models;

namespace projet_club_sportif.Controllers
{
    [Authorize]
    public class stagesController : Controller
    {
        private Stage stage;
        private LieuDAO lieuDao;

        public stagesController() : this(new Stage(), new LieuDAO())
        {

        }

        private stagesController(Stage unStage, LieuDAO UnLieuDao)
        {
            stage = unStage;
            lieuDao = UnLieuDao;
        }

        // GET: stages
        public ActionResult Index()
        {
            var stages = stage.GetAll();
            return View(stages.ToList());
        }

        // GET: stages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            stage.Find((int)id);
            if (stage == null)
            {
                return HttpNotFound();
            }
            return View(stage);
        }

        // GET: stages/Create
        public ActionResult Create()
        {
            ViewBag.lieux = lieuDao.GetAllForEvents();

            return View(stage);
        }

        // POST: stages/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Stage unStage)
        {
            if (ModelState.IsValid)
            {
                stage.Create(unStage);
                return RedirectToAction("Index");
            }

            return View(stage);
        }

        // GET: stages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            stage.Find((int) id);
            if (stage == null)
            {
                return HttpNotFound();
            }

            ViewBag.lieux = lieuDao.GetAllForEvents();

            return View(stage);
        }

        // POST: stages/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Stage unStage)
        {
            if (ModelState.IsValid)
            {
                stage.Find(unStage.fk_evenement);
                stage.Update(unStage);
                return RedirectToAction("Index");
            }

            return View(stage);
        }

        // GET: stages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            stage = stage.Find((int) id);
            if (stage == null)
            {
                return HttpNotFound();
            }
            return View(stage);
        }

        // POST: stages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            stage.Find(id);
            stage.Delete();
            return RedirectToAction("Index");
        }

    }
}

Code/projet_club_sportif/Controllers/themesController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using projet_club_sportif.Models;

namespace projet_club_sportif.Controllers
{
    [Authorize]
    public class themesController : Controller
    {
        private DAO<T_Theme> themeDao;

        public themesController() : this(new ThemeDAO())
        {

        }

        private themesController(ThemeDAO UnThemeDao)
        {
            themeDao = UnThemeDao;
        }

        // GET: themes
        public ActionResult Index()
        {
            return View(themeDao.GetAll().ToList());
        }

        // GET: themes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Theme unTheme = themeDao.Find((int) id);
            if (unTheme == null)
            {
                return HttpNotFound();
            }
            return View(unTheme);
        }

        // GET: themes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: themes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(T_Theme unTheme)
        {
            if (ModelState.IsValid)
            {
                themeDao.Create(unTheme);
                return RedirectToAction("Index");
            }

            return View(unTheme);
        }

        // GET: themes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Theme theme = themeDao.Find((int) id);
            if (theme == null)
            {
                return HttpNotFound();
            }
            return View(theme);
        }

        // POST: themes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(T_Theme unTheme)
        {
            if (ModelState.IsValid)
            {
                themeDao.Update(unTheme);
                return RedirectToAction("Index");
            }
            return View(unTheme);
        }

        // GET: themes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Theme unTheme = themeDao.Find((int) id);
            if (unTheme == null)
            {
                return HttpNotFound();
            }
            return View(unTheme);
        }

        // POST: themes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            T_Theme unTheme = themeDao.Find(id);
            themeDao.Delete(unTheme);
            return RedirectToAction("Index");
        }
    }
}

Code/projet_club_sportif/Views/themes/Create.cshtml
@model projet_club_sportif.Models.T_Theme

@{
    ViewBag.Title = "Créer";
}

<h2>Créer</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>theme</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.theme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.theme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.theme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

@section scripts
{
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Code/projet_club_sportif/Views/themes/Delete.cshtml
@model projet_club_sportif.Models.T_Theme

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Êtes-vous sure de vouloir supprimer cet élément ?</h3>
<div>
    <h4>theme</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.theme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.theme)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Retour à la liste", "Index")
        </div>
    }
</div>

Code/projet_club_sportif/Views/themes/Details.cshtml
@model projet_club_sportif.Models.T_Theme

@{
    ViewBag.Title = "Détails";
}

<h2>Détails</h2>

<div>
    <h4>theme</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.theme)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.theme)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.pk_theme }) |
    @Html.ActionLink("Retour à la liste", "Index")
</p>

Code/projet_club_sportif/Views/themes/Edit.cshtml
@model projet_club_sportif.Models.T_Theme

@{
    ViewBag.Title = "Modifier";
}

<h2>Modifier</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>theme</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.pk_theme)

        <div class="form-group">
            @Html.LabelFor(model => model.theme, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.theme, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.theme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

@section scripts
{
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Code/projet_club_sportif/Views/themes/Index.cshtml
@model IEnumerable<projet_club_sportif.Models.T_Theme>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Créer un nouveau", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.theme)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.theme)
        </td>
        <td>
            @Html.ActionLink("Modifier", "Edit", new { id=item.pk_theme }) |
            @Html.ActionLink("Détails", "Details", new { id=item.pk_theme }) |
            @Html.ActionLink("Supprimer", "Delete", new { id=item.pk_theme })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Retour au menu", "Index", "menu")
    @Html.ActionLink("Retour aux stages", "Index", "stages")
    @Html.ActionLink("Retour aux cours et examens", "Index", "cours_et_examen")
</div>