Code/projet_club_sportif/Controllers/loginController.cs
using System.Web.Security;
using System.Web.Mvc;
using projet_club_sportif.Models;
using projet_club_sportif.ViewModels;

namespace projet_club_sportif.Controllers
{
    public class loginController : Controller
    {
        private PersonneDAO PersonneDao;
        private PersonneViewModel leViewModel;

        public loginController() : this(new PersonneDAO())
        {

        }

        private loginController(PersonneDAO UnPersonneDao)
        {
            PersonneDao = UnPersonneDao;
        }


        public ActionResult Index()
        {
            leViewModel = new PersonneViewModel { Authentifie = HttpContext.User.Identity.IsAuthenticated };
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                leViewModel.Personne = PersonneDao.FindByEmail(HttpContext.User.Identity.Name);
            }
            return View(leViewModel);
        }


        [HttpPost]
        public ActionResult Index(PersonneViewModel viewModel, string ReturnUrl)
        {
            if (ModelState.IsValid)
            {
                if (PersonneDao.Authenticate(viewModel.Personne.email, viewModel.Personne.mdp))
                {
                    T_Personne personne = PersonneDao.FindByEmail(viewModel.Personne.email);
                    FormsAuthentication.SetAuthCookie(personne.email.ToString(), false);
                    if (!string.IsNullOrWhiteSpace(ReturnUrl) && Url.IsLocalUrl(ReturnUrl))
                    {
                        return Redirect(ReturnUrl);
                    }
                    
                    //si pas de return url
                    if(personne.staff)
                        return RedirectToAction("Instructeur", "menu");
                    else
                        return RedirectToAction("Eleve", "menu");
                }
                ModelState.AddModelError("Personne.email", "Email et/ou mot de passe incorrect(s)");
            }
            return View(viewModel);
        }

        public ActionResult CreerCompte()
        {
            return View();
        }

        public ActionResult Deconnexion()
        {
            FormsAuthentication.SignOut();
            return Redirect("/");
        }
    }
}

Code/projet_club_sportif/Views/Shared/Erreur.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Erreur</title>
</head>
<body>
    <div> 
        Coucou, tu t'es planté !
    </div>
</body>
</html>

Code/projet_club_sportif/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gestion d'un club sportif</title>
    
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    @RenderSection("css", required: false)
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gestion d'un club sportif", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Déconnexion", "Deconnexion", "login")</li>
                </ul>
            </div>
        </div>
    </div>

    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Code/projet_club_sportif/Views/Shared/_LayoutSansLogout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gestion d'un club sportif</title>
    
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" type="text/css" />
    @RenderSection("css", required: false)
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gestion d'un club sportif", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/menu/JavaScript.js"></script>
    
    @RenderSection("scripts", required: false)
</body>
</html>

Code/projet_club_sportif/Views/Shared/_menu_instructeur.cshtml
<div id="menu-membre">
    <ul id="affiche">
        <li>@Html.ActionLink("Consulter L'historique", "Instructeur_Gerer_Historique", "menu")</li>
        <li>@Html.ActionLink("Gérer les données étudiantes", "Index", "compte")</li>
        <li>@Html.ActionLink("Gérer les évènements", "Instructeur_Gerer_Les_Evenements", "menu")</li>
        <li>@Html.ActionLink("Gérer son compte", "Gerer_Son_Compte", "compte")</li>
        <li>@Html.ActionLink("Gérer ses inscriptions à des événements", "Gerer_Ses_Inscriptions", "menu")</li>
        <li>@Html.ActionLink("Gérer les inscriptions d'un pratiquant", "Instructeur_Gerer_Inscription_Eleve", "menu")</li>
    </ul>
</div>

Code/projet_club_sportif/Views/Shared/_menu_pratiquant.cshtml
<div id="menu-membre">
    <ul>
        <li>@Html.ActionLink("Consulter son historique", "Eleve_Consulter_Son_Historique", "menu")</li>
        <li>@Html.ActionLink("Gérer son compte", "Gerer_Son_Compte", "compte")</li>
        <li>@Html.ActionLink("Gérer ses inscriptions à des événements", "Gerer_Ses_Inscriptions", "menu")</li>
    </ul>
</div>