Code/projet_club_sportif/Models/Competition/T_Competition.cs
namespace projet_club_sportif.Models
{
    using System.ComponentModel.DataAnnotations;

    public class T_Competition
    {
        public int fk_evenement { get; set; }

        [Display(Name = "Titre de la compétition:")]
        [StringLength(150, ErrorMessage = "La compétition doit faire moins de {1} charactères.")]
        public string titre { get; set; }

    }
}

Code/projet_club_sportif/Controllers/categoriesController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using projet_club_sportif.Models;

namespace projet_club_sportif.Controllers
{
    [Authorize]
    public class categoriesController : Controller
    {
        private DAO<T_Categorie> CategorieDao;

        public categoriesController() : this(new CategorieDAO())
        {

        }

        private categoriesController(CategorieDAO UnCategorieDao)
        {
            CategorieDao = UnCategorieDao;
        }

        // GET: categories
        public ActionResult Index()
        {
            return View(CategorieDao.GetAll().ToList());
        }

        // GET: categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Categorie categorie = CategorieDao.Find((int) id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // GET: categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: categories/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(T_Categorie uneCategorie)
        {
            if (ModelState.IsValid)
            {
                CategorieDao.Create(uneCategorie);
                return RedirectToAction("Index");
            }

            return View(uneCategorie);
        }

        // GET: categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Categorie categorie = CategorieDao.Find((int) id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // POST: categories/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(T_Categorie uneCategorie)
        {
            if (ModelState.IsValid)
            {
                CategorieDao.Update(uneCategorie);
                return RedirectToAction("Index");
            }
            return View(uneCategorie);
        }

        // GET: categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_Categorie categorie = CategorieDao.Find((int) id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // POST: categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            T_Categorie categorie = CategorieDao.Find(id);
            CategorieDao.Delete(categorie);
            return RedirectToAction("Index");
        }
    }
}

Code/projet_club_sportif/Controllers/competitionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using projet_club_sportif.Models;

namespace projet_club_sportif.Controllers
{
    [Authorize]
    public class competitionsController : Controller
    {
        private Competition competition;
        private LieuDAO lieuDao;

        public competitionsController() : this(new Competition(), new LieuDAO())
        {

        }

        private competitionsController(Competition UneCompetition, LieuDAO UnLieuDao)
        {
            competition = UneCompetition;
            lieuDao = UnLieuDao;
        }

        // GET: competitions
        public ActionResult Index()
        {
            var competitions = competition.GetAll();
            return View(competitions.ToList());
        }

        // GET: competitions/Create
        public ActionResult GetPrix(int num_prix)
        {
            ViewBag.numPrix = num_prix;

            return View(competition);
        }

        // GET: competitions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            competition.Find((int) id);
            if (competition == null)
            {
                return HttpNotFound();
            }
            return View(competition);
        }

        // GET: competitions/Create
        public ActionResult Create()
        {
            ViewBag.lieux = lieuDao.GetAllForEvents();

            return View(competition);
        }

        // POST: competitions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Competition uneCompetition)
        {
            //variables
            var form = Request.Form;
            string[] arrayIndex = form.GetValues("Index");
            bool conversionOk = false;

            uneCompetition.listPrix = new List<T_PrixCompetition>();
            int nbCategories;
            decimal prix;
            foreach (string unIndex in arrayIndex)
            {
                T_PrixCompetition unPrix = new T_PrixCompetition();
                conversionOk = int.TryParse(form.Get("listPrix[" + unIndex + "].nbCategories"), out nbCategories);
                conversionOk &= decimal.TryParse(form.Get("listPrix[" + unIndex + "].prix"), out prix);
                if (conversionOk)
                {
                    unPrix.nbCategories = nbCategories;
                    unPrix.prix = prix;
                    uneCompetition.listPrix.Add(unPrix);
                }
            }

            //validation
            ModelState.Clear();
            TryValidateModel(uneCompetition);

            if (ModelState.IsValid)
            {
                competition.Create(uneCompetition);
                return RedirectToAction("Index");
            }

            return View(uneCompetition);
        }

        // GET: competitions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            competition.Find((int) id);
            if (competition == null)
            {
                return HttpNotFound();
            }

            ViewBag.lieux = lieuDao.GetAllForEvents();

            return View(competition);
        }

        // POST: competitions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Competition uneCompetition)
        {
            //variables
            var form = Request.Form;
            string[] arrayIndex = form.GetValues("Index");
            bool conversionOk = false;

            uneCompetition.listPrix = new List<T_PrixCompetition>();
            int nbCategories;
            decimal prix;
            foreach (string unIndex in arrayIndex)
            {
                T_PrixCompetition unPrix = new T_PrixCompetition();
                conversionOk = int.TryParse(form.Get("listPrix[" + unIndex + "].nbCategories"), out nbCategories);
                conversionOk &= decimal.TryParse(form.Get("listPrix[" + unIndex + "].prix"), out prix);
                if (conversionOk)
                {
                    unPrix.nbCategories = nbCategories;
                    unPrix.prix = prix;
                    uneCompetition.listPrix.Add(unPrix);
                }
            }

            //validation
            ModelState.Clear();
            TryValidateModel(uneCompetition);

            if (ModelState.IsValid)
            {
                competition.Find(uneCompetition.fk_evenement);
                competition.Update(uneCompetition);
                return RedirectToAction("Index");
            }

            return View(uneCompetition);
        }

        // GET: competitions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            competition.Find((int) id);
            if (competition == null)
            {
                return HttpNotFound();
            }
            return View(competition);
        }

        // POST: competitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            competition.Find(id);
            competition.Delete();
            return RedirectToAction("Index");
        }

    }
}

Code/projet_club_sportif/Views/competitions/Create.cshtml
@model projet_club_sportif.Models.Competition

@{
    ViewBag.Title = "Créer";
}

@section css
{
    <link href="~/Scripts/chosen_v1.8.7/chosen.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/jquery-ui-1.12.1.custom/jquery-ui.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Scripts/timepicker/jquery.timepicker.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
}

<h2>Create</h2>


@using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "create-competition-form" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>competition</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.titre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoriesSelectedId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.categoriesSelectedId, new MultiSelectList(Model.categories, "pk_categorie", "categorie", Model.categoriesSelectedId), new { @class = "form-control chosen" })
                @Html.ValidationMessageFor(model => model.categoriesSelectedId, "", htmlAttributes: new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateDebut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateDebut, "DateTimeStart", new { htmlAttributes = new { @class = "form-control " } })
                @Html.HiddenFor(model => model.dateDebut)
                @Html.ValidationMessageFor(model => model.dateDebut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateFin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateFin, "DateTimeEnd", new { htmlAttributes = new { @class = "form -control " } })
                @Html.HiddenFor(model => model.dateFin)
                @Html.ValidationMessageFor(model => model.dateFin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fk_lieu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <table id='table-choix-lieu' class='display'>
                    <thead>
                        <tr>
                            <th>Salle</th>
                            <th>Adresse</th>
                            <th>Code Postal</th>
                            <th>Ville</th>
                            <th>Pays</th>
                            <th></th>
                        </tr>
                        <tr>
                            <th><input type="text" placeholder="" /></th>
                            <th><input type="text" placeholder="" /></th>
                            <th><input type="text" placeholder="" /></th>
                            <th><input type="text" placeholder="" /></th>
                            <th><input type="text" placeholder="" /></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (projet_club_sportif.Models.T_Lieu unLieu in ViewBag.lieux)
                {
                            <tr>
                                <td>@Html.DisplayName(unLieu.salle)</td>
                                <td>@Html.DisplayName(unLieu.adresse)</td>
                                <td>@Html.DisplayName(unLieu.cp.ToString())</td>
                                <td>@Html.DisplayName(unLieu.ville)</td>
                                <td>@Html.DisplayName(unLieu.pays)</td>
                                <td>
                                    @Html.RadioButtonFor(m => m.fk_lieu, unLieu.pk_lieu)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                @Html.ValidationMessageFor(model => model.fk_lieu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.organisateursSelectedId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.organisateursSelectedId, new MultiSelectList(Model.organisateurs, "pk_personne", "nom", Model.organisateursSelectedId), new { @class = "form-control chosen" })
                @Html.ValidationMessageFor(model => model.organisateursSelectedId, "", htmlAttributes: new { @class = "text-danger" })
            </div>
        </div>

        <div id="prix" class="form-horizontal">@Html.EditorFor(model => model.listPrix, "ListTPrixCompetition")</div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Ajouter un prix" class="btn btn-default" id="AddPrixButton" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Supprimer le dernier prix" class="btn btn-default" id="SupprimerPrixButton" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

@section scripts
{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="~/Scripts/chosen_v1.8.7/chosen.jquery.min.js"></script>

    <script src="~/Scripts/timepicker/jquery.timepicker.min.js"></script>
    <script src="~/Scripts/moment-with-locales.min.js"></script>
    <script src="~/Scripts/datepair/jquery.datepair.min.js"></script>

    <script src="~/Scripts/competition/create.js"></script>
}

Code/projet_club_sportif/Views/competitions/Delete.cshtml
@model projet_club_sportif.Models.Competition

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>competition</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categories)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoriesSelectedId, "ListTCategories")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.listPrix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.listPrix, "ListTPrixCompetition")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateDebut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateDebut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.salle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ville)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ville)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pays)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pays)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.organisateursSelectedId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.organisateursSelectedId, "ListOrganisateursEtParticipants")
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Retour à la liste", "Index")
        </div>
    }
</div>

Code/projet_club_sportif/Views/competitions/Details.cshtml
@model projet_club_sportif.Models.Competition

@{
    ViewBag.Title = "Détails";
}

<h2>Détails</h2>

<div>
    <h4>competition</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categories)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoriesSelectedId, "ListTCategories")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.listPrix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.listPrix, "ListTPrixCompetition")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateDebut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateDebut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.salle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ville)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ville)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pays)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pays)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.organisateursSelectedId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.organisateursSelectedId, "ListOrganisateursEtParticipants")
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.fk_evenement }) |
    @Html.ActionLink("Retour à la liste", "Index")
</p>

Code/projet_club_sportif/Views/competitions/Edit.cshtml
@model projet_club_sportif.Models.Competition

@{
    ViewBag.Title = "Modifier";
}

@section css
{
    <link href="~/Scripts/chosen_v1.8.7/chosen.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/jquery-ui-1.12.1.custom/jquery-ui.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Scripts/timepicker/jquery.timepicker.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    
}

<h2>Modifier</h2>


@using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "edit-competition-form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>competition</h4>
        <hr />
        @Html.HiddenFor(model => model.fk_evenement)

        <div class="form-group">
            <div class="col-md-10 error">

            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.titre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categoriesSelectedId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.categoriesSelectedId, new MultiSelectList(Model.categories, "pk_categorie", "categorie", Model.categoriesSelectedId), new { @class = "form-control chosen" })
                @Html.ValidationMessageFor(model => model.categoriesSelectedId, "", htmlAttributes: new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateDebut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateDebut, "DateTimeStart", new { htmlAttributes = new { @class = "form-control " } })
                @Html.HiddenFor(model => model.dateDebut)
                @Html.ValidationMessageFor(model => model.dateDebut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateFin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateFin, "DateTimeEnd", new { htmlAttributes = new { @class = "form -control " } })
                @Html.HiddenFor(model => model.dateFin)
                @Html.ValidationMessageFor(model => model.dateFin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fk_lieu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <table id='table-choix-lieu' class='display'>
                    <thead>
                        <tr>
                            <th>Salle</th>
                            <th>Adresse</th>
                            <th>Code Postal</th>
                            <th>Ville</th>
                            <th>Pays</th>
                            <th></th>
                        </tr>
                        <tr>
                            <th><input type="text" placeholder="" /></th>
                            <th><input type="text" placeholder="" /></th>
                            <th><input type="text" placeholder="" /></th>
                            <th><input type="text" placeholder="" /></th>
                            <th><input type="text" placeholder="" /></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (projet_club_sportif.Models.T_Lieu unLieu in ViewBag.lieux)
                        {
                            <tr>
                                <td>@Html.DisplayName(unLieu.salle)</td>
                                <td>@Html.DisplayName(unLieu.adresse)</td>
                                <td>@Html.DisplayName(unLieu.cp.ToString())</td>
                                <td>@Html.DisplayName(unLieu.ville)</td>
                                <td>@Html.DisplayName(unLieu.pays)</td>
                                <td>
                                    @Html.RadioButtonFor(m => m.fk_lieu, unLieu.pk_lieu)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                @Html.ValidationMessageFor(model => model.fk_lieu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.organisateursSelectedId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.organisateursSelectedId, new MultiSelectList(Model.organisateurs, "pk_personne", "nom", Model.organisateursSelectedId), new { @class = "form-control chosen" })
                @Html.ValidationMessageFor(model => model.organisateursSelectedId, "", htmlAttributes: new { @class = "text-danger" })
            </div>
        </div>

        <div id="prix" class="form-horizontal">@Html.EditorFor(model => model.listPrix, "ListTPrixCompetition")</div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Ajouter un prix" class="btn btn-default" id="AddPrixButton" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Supprimer le dernier prix" class="btn btn-default" id="SupprimerPrixButton" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

@section scripts
{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="~/Scripts/chosen_v1.8.7/chosen.jquery.min.js"></script>

    <script src="~/Scripts/timepicker/jquery.timepicker.min.js"></script>
    <script src="~/Scripts/moment-with-locales.min.js"></script>
    <script src="~/Scripts/datepair/jquery.datepair.min.js"></script>

    <script src="~/Scripts/competition/edit.js"></script>
}

Code/projet_club_sportif/Views/competitions/Index.cshtml
@model IEnumerable<projet_club_sportif.Models.Competition>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<ul>
    <li>@Html.ActionLink("Créer une nouvelle catégorie", "Index", "categories")</li>
    <li>@Html.ActionLink("Créer une nouvelle compétition", "Create")</li>
</ul>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.titre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.categories)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateDebut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateFin)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.titre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.categoriesSelectedId, "ListTCategories")
        </td>
        <td>
            @Html.Raw(item.dateDebut.ToString("dd/MM/yyyy HH:mm"))
        </td>
        <td>
            @Html.Raw(item.dateFin.ToString("dd/MM/yyyy HH:mm"))
        </td>
        <td>
            @Html.ActionLink("Modifier", "Edit", new { id=item.fk_evenement }) |
            @Html.ActionLink("Détails", "Details", new { id=item.fk_evenement }) |
            @Html.ActionLink("Supprimer", "Delete", new { id=item.fk_evenement })
        </td>
    </tr>
}
</table>

<div>
    @Html.ActionLink("Retour", "Instructeur_Gerer_Les_Evenements",  "menu")
</div>